// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGi9H0-In5L4vchXXu_swKitPX5iSVuBw',
    appId: '1:76695965127:web:68491829c738e1df681de2',
    messagingSenderId: '76695965127',
    projectId: 'payvera-42eca',
    authDomain: 'payvera-42eca.firebaseapp.com',
    storageBucket: 'payvera-42eca.firebasestorage.app',
    measurementId: 'G-5LR5NBVL3L',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGi9H0-In5L4vchXXu_swKitPX5iSVuBw',
    appId: '1:76695965127:web:468a679d41dd4d23681de2',
    messagingSenderId: '76695965127',
    projectId: 'payvera-42eca',
    authDomain: 'payvera-42eca.firebaseapp.com',
    storageBucket: 'payvera-42eca.firebasestorage.app',
    measurementId: 'G-CM815G2YFS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGsTg7Nu_6Y3qCC3MvT7W9fJXgxhcfe2U',
    appId: '1:76695965127:ios:a6b581c4590fafbe681de2',
    messagingSenderId: '76695965127',
    projectId: 'payvera-42eca',
    storageBucket: 'payvera-42eca.firebasestorage.app',
    iosBundleId: 'com.example.payveraMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGsTg7Nu_6Y3qCC3MvT7W9fJXgxhcfe2U',
    appId: '1:76695965127:ios:a6b581c4590fafbe681de2',
    messagingSenderId: '76695965127',
    projectId: 'payvera-42eca',
    storageBucket: 'payvera-42eca.firebasestorage.app',
    iosBundleId: 'com.example.payveraMobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu5bij-TNHBfZJwXGQuRlfNJOLB9V-fqQ',
    appId: '1:76695965127:android:95cb7f93b090adba681de2',
    messagingSenderId: '76695965127',
    projectId: 'payvera-42eca',
    storageBucket: 'payvera-42eca.firebasestorage.app',
  );
}
